In [27]:
import pandas as pd
import numpy as np

In [28]:
df = pd.read_csv("housing.csv")

In [29]:
housing["OCEAN_PROXIMITY"] = df["ocean_proximity"]
housing

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
12655    -121.46     38.52                29.0       3873.0           797.0   
15502    -117.23     33.09                 7.0       5320.0           855.0   
2908     -119.04     35.37                44.0       1618.0           310.0   
14053    -117.13     32.75                24.0       1877.0           519.0   
20496    -118.70     34.28                27.0       3536.0           646.0   
...          ...       ...                 ...          ...             ...   
15174    -117.07     33.03                14.0       6665.0          1231.0   
12661    -121.42     38.51                15.0       7901.0          1422.0   
19263    -122.72     38.44                48.0        707.0           166.0   
19140    -122.70     38.31                14.0       3155.0           580.0   
19773    -122.14     39.97                27.0       1079.0           222.0   

       population  households  median_income ocean_proximity OCEAN_PROXIMITY  
12655      2237.0       706.0         2.1736          INLAND          INLAND  
15502      2015.0       768.0         6.3373      NEAR OCEAN      NEAR OCEAN  
2908        667.0       300.0         2.8750          INLAND          INLAND  
14053       898.0       483.0         2.2264      NEAR OCEAN      NEAR OCEAN  
20496      1837.0       580.0         4.4964       <1H OCEAN       <1H OCEAN  
...           ...         ...            ...             ...             ...  
15174      2026.0      1001.0         5.0900       <1H OCEAN       <1H OCEAN  
12661      4769.0      1418.0         2.8139          INLAND          INLAND  
19263       458.0       172.0         3.1797       <1H OCEAN       <1H OCEAN  
19140      1208.0       501.0         4.1964       <1H OCEAN       <1H OCEAN  
19773       625.0       197.0         3.1319          INLAND          INLAND  

[16512 rows x 10 columns]

In [30]:
set(housing["OCEAN_PROXIMITY"])

{'<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'}

In [31]:
housing_cat = housing[["ocean_proximity"]]
housing_cat

ocean_proximity
12655          INLAND
15502      NEAR OCEAN
2908           INLAND
14053      NEAR OCEAN
20496       <1H OCEAN
...               ...
15174       <1H OCEAN
12661          INLAND
19263       <1H OCEAN
19140       <1H OCEAN
19773          INLAND

[16512 rows x 1 columns]

In [32]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat)
housing_cat_encoded

array([[1.],
       [4.],
       [1.],
       ...,
       [0.],
       [0.],
       [1.]])

In [33]:
ordinal_encoder.categories_

[array(['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'],
       dtype=object)]

In [46]:
from sklearn.preprocessing import OneHotEncoder
cat_encoder = OneHotEncoder()
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [49]:
housing_cat = pd.DataFrame(housing_cat , columns = ["<1H OCEAN" , "Inland" , "Island" , "Near Bay" , "Near Ocean"] , index = housing.index )
housing_cat

<1H OCEAN  Inland  Island  Near Bay  Near Ocean
12655        0.0     1.0     0.0       0.0         0.0
15502        0.0     0.0     0.0       0.0         1.0
2908         0.0     1.0     0.0       0.0         0.0
14053        0.0     0.0     0.0       0.0         1.0
20496        1.0     0.0     0.0       0.0         0.0
...          ...     ...     ...       ...         ...
15174        1.0     0.0     0.0       0.0         0.0
12661        0.0     1.0     0.0       0.0         0.0
19263        1.0     0.0     0.0       0.0         0.0
19140        1.0     0.0     0.0       0.0         0.0
19773        0.0     1.0     0.0       0.0         0.0

[16512 rows x 5 columns]

In [50]:
df = pd.concat([df, housing_cat], axis = 1)
df

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0   
1        -122.22     37.86                21.0       7099.0          1106.0   
2        -122.24     37.85                52.0       1467.0           190.0   
3        -122.25     37.85                52.0       1274.0           235.0   
4        -122.25     37.85                52.0       1627.0           280.0   
...          ...       ...                 ...          ...             ...   
20635    -121.09     39.48                25.0       1665.0           374.0   
20636    -121.21     39.49                18.0        697.0           150.0   
20637    -121.22     39.43                17.0       2254.0           485.0   
20638    -121.32     39.43                18.0       1860.0           409.0   
20639    -121.24     39.37                16.0       2785.0           616.0   

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0   
1          2401.0      1138.0         8.3014            358500.0   
2           496.0       177.0         7.2574            352100.0   
3           558.0       219.0         5.6431            341300.0   
4           565.0       259.0         3.8462            342200.0   
...           ...         ...            ...                 ...   
20635       845.0       330.0         1.5603             78100.0   
20636       356.0       114.0         2.5568             77100.0   
20637      1007.0       433.0         1.7000             92300.0   
20638       741.0       349.0         1.8672             84700.0   
20639      1387.0       530.0         2.3886             89400.0   

      ocean_proximity ocean_proximity  <1H OCEAN  Inland  Island  Near Bay  \
0            NEAR BAY        NEAR BAY        0.0     0.0     0.0       1.0   
1            NEAR BAY        NEAR BAY        0.0     0.0     0.0       1.0   
2            NEAR BAY        NEAR BAY        0.0     0.0     0.0       1.0   
3            NEAR BAY        NEAR BAY        0.0     0.0     0.0       1.0   
4            NEAR BAY        NEAR BAY        0.0     0.0     0.0       1.0   
...               ...             ...        ...     ...     ...       ...   
20635          INLAND          INLAND        0.0     1.0     0.0       0.0   
20636          INLAND          INLAND        0.0     1.0     0.0       0.0   
20637          INLAND          INLAND        0.0     1.0     0.0       0.0   
20638          INLAND          INLAND        0.0     1.0     0.0       0.0   
20639          INLAND             NaN        NaN     NaN     NaN       NaN   

       Near Ocean  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0  
...           ...  
20635         0.0  
20636         0.0  
20637         0.0  
20638         0.0  
20639         NaN  

[20640 rows x 16 columns]

In [51]:
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler(feature_range = (-1, 1))
housing_num_min_max_scaled = min_max_scaler.fit_transform(housing_num)

In [52]:
housing_num_min_max_scaled

array([[-0.42430279,  0.27098831,  0.09803922, ..., -0.87477228,
        -0.73711725, -0.76914801],
       [ 0.41832669, -0.88310308, -0.76470588, ..., -0.88721657,
        -0.71396565, -0.19485248],
       [ 0.05776892, -0.39851222,  0.68627451, ..., -0.96277923,
        -0.88872293, -0.67240452],
       ...,
       [-0.6752988 ,  0.25398512,  0.84313725, ..., -0.9744948 ,
        -0.93651979, -0.63037751],
       [-0.67131474,  0.22635494, -0.49019608, ..., -0.93245326,
        -0.81366692, -0.49014496],
       [-0.55976096,  0.57917109,  0.01960784, ..., -0.96513355,
        -0.92718447, -0.63697052]])

In [55]:
from sklearn.preprocessing import StandardScaler
Standard_Scaler = StandardScaler()
housing_num_std_scaled = Standard_Scaler.fit_transform(housing_num)

In [56]:
housing_num_std_scaled

array([[-0.94135046,  1.34743822,  0.02756357, ...,  0.73260236,
         0.55628602, -0.8936472 ],
       [ 1.17178212, -1.19243966, -1.72201763, ...,  0.53361152,
         0.72131799,  1.292168  ],
       [ 0.26758118, -0.1259716 ,  1.22045984, ..., -0.67467519,
        -0.52440722, -0.52543365],
       ...,
       [-1.5707942 ,  1.31001828,  1.53856552, ..., -0.86201341,
        -0.86511838, -0.36547546],
       [-1.56080303,  1.2492109 , -1.1653327 , ..., -0.18974707,
         0.01061579,  0.16826095],
       [-1.28105026,  2.02567448, -0.13148926, ..., -0.71232211,
        -0.79857323, -0.390569  ]])